<?php
// Include the main TCPDF library (search for installation path).
require_once __DIR__ . '/vendor/autoload.php';

// Create a class that extends TCPDF
class MYPDF extends TCPDF {

    // Colored table
    public function ColoredTable($header, $data) {
        // Colors, line width, and bold font
        $this->SetFillColor(255, 0, 0); // Red color for the header
        $this->SetTextColor(255); // White text
        $this->SetDrawColor(128, 0, 0); // Dark red border
        $this->SetLineWidth(0.3);
        $this->SetFont('', 'B');
        
        // Header
        $w = array(40, 35, 40); // Column widths (adjusted for 3 columns)
        $num_headers = count($header);
        for($i = 0; $i < $num_headers; ++$i) {
            $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', 1); // Header cell
        }
        $this->Ln();
        
        // Color and font restoration
        $this->SetFillColor(224, 235, 255); // Light blue fill for the data rows
        $this->SetTextColor(0); // Black text for the data
        $this->SetFont('');
        
        // Data
        $fill = 0;
        foreach($data as $row) {
            $this->Cell($w[0], 6, $row[0], 'LR', 0, 'L', $fill); // Last Name
            $this->Cell($w[1], 6, $row[1], 'LR', 0, 'L', $fill); // Scholarship Type
            $this->Cell($w[2], 6, $row[2], 'LR', 0, 'L', $fill); // Date Applied
            $this->Ln();
            $fill = !$fill; // Toggle fill for alternating rows
        }
        $this->Cell(array_sum($w), 0, '', 'T'); // Bottom border
    }
}

// Fetch data from the database (in your case, this comes from your `generate.php` query)
include('includes/db.php');
$sql = "SELECT id, sid, sfname, applied_on, slname, s_scholar_status, s_account_status, s_scholarship_type  
        FROM students 
        WHERE is_scholar = 1 AND s_account_status = 'Valid'";

$result = $conn->query($sql);

if (!$result) {
    die("Query Failed: " . $conn->error);
}

// Create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Company');
$pdf->SetTitle('Scholarship Report');
$pdf->SetSubject('Report for Valid Scholars');
$pdf->SetKeywords('TCPDF, PDF, report, scholars');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Scholarship Report', 'Generated by Your Company');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Column titles (Header)
$header = array('Last Name', 'Scholarship Type', 'Date Applied');

// Prepare the data to be printed in the table
$data = array();
while ($row = $result->fetch_assoc()) {
    $data[] = array($row['slname'], $row['s_scholarship_type'], date("Y-m-d", strtotime($row['applied_on'])));
}

// Print the colored table with the data
$pdf->ColoredTable($header, $data);

// Output the PDF document
$pdf->Output('scholarship_report.pdf', 'I');
?>
